
# py.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b',(P\xbfDC7Z\x830\x16Z6n\xbf\n'
    
_lr_action_items = {'TOKO':([0,2,3,13,19,],[1,1,1,1,-4,]),'$end':([0,2,4,7,13,19,20,],[-3,-3,0,-1,-3,-4,-2,]),'INFOSC':([5,9,10,15,21,],[-7,14,-7,-6,-8,]),'INFOSO':([1,],[5,]),'TOKC':([12,],[19,]),'ATT':([11,17,23,],[18,18,-11,]),'ITC':([11,16,17,22,23,],[-10,21,-10,-9,-11,]),'DIVC':([2,3,7,8,13,19,20,],[-3,-3,-1,13,-3,-4,-2,]),'WORD':([6,14,],[12,-5,]),'VAL':([18,],[23,]),'ITO':([5,10,21,],[11,11,-8,]),'DIVO':([0,2,3,13,19,],[3,3,3,3,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lstitems':([5,10,],[9,15,]),'items':([5,10,],[10,10,]),'infos':([1,],[6,]),'lstattval':([11,17,],[16,22,]),'tok':([0,2,3,13,],[2,2,2,2,]),'attval':([11,17,],[17,17,]),'lsttok':([0,2,3,13,],[4,7,8,20,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lsttok","S'",1,None,None,None),
  ('lsttok -> tok lsttok','lsttok',2,'p_lsttok','./Tokxml.py',166),
  ('lsttok -> DIVO lsttok DIVC lsttok','lsttok',4,'p_lsttok','./Tokxml.py',167),
  ('lsttok -> <empty>','lsttok',0,'p_lsttok','./Tokxml.py',168),
  ('tok -> TOKO infos WORD TOKC','tok',4,'p_tok','./Tokxml.py',180),
  ('infos -> INFOSO lstitems INFOSC','infos',3,'p_infos','./Tokxml.py',189),
  ('lstitems -> items lstitems','lstitems',2,'p_lstitems','./Tokxml.py',195),
  ('lstitems -> <empty>','lstitems',0,'p_lstitems','./Tokxml.py',196),
  ('items -> ITO lstattval ITC','items',3,'p_items','./Tokxml.py',205),
  ('lstattval -> attval lstattval','lstattval',2,'p_lstattval','./Tokxml.py',211),
  ('lstattval -> <empty>','lstattval',0,'p_lstattval','./Tokxml.py',212),
  ('attval -> ATT VAL','attval',2,'p_attval','./Tokxml.py',224),
]
